[package]
name = "tokio-codec-msgpack"
version = "0.1.0"
authors = ["Andrew Kubera <andrew.kubera@floss.email>"]
edition = "2018"

[dependencies]
tokio-codec = "0.2.0-alpha.6"
rmpv = "*"
rmp-serde = "*"
bytes = "0.4.12"

[dev-dependencies]
tokio-io = "0.2.0-alpha.6"
